### ISSUE TITLE
Dimension mismatch with basis_states

### ISSUE THREAD

**Issue by phpisciuneri** [ajoshpratt/p53-tutorial#1]
To pick up from our discussion via email. 

Here are my Env variables on Frank `module load westpa/anaconda2-2.4.1`:

``` bash
php8@login0b:~/run/p53-tutorial$ echo $WEST_PYTHON
/opt/sam/anaconda/2.4.1/bin/python2.7
php8@login0b:~/run/p53-tutorial$ echo $WEST_ROOT  
/opt/sam/westpa-mpi
```

If I run the p53 tutorial with changes to use my environment I get the following error:

``` bash
php8@login0b:~/run/p53-tutorial$ ./init.sh 
simulation p53-tutorial root is /ihome/pgivi/php8/run/p53-tutorial
Creating HDF5 file '/ihome/pgivi/php8/run/p53-tutorial/west.h5'
0 target state(s) present
Calculating progress coordinate values for basis states.
Traceback (most recent call last):
  File "/opt/sam/westpa-mpi/lib/cmds/w_init.py", line 125, in <module>
    suppress_we=args.shotgun)
  File "/opt/sam/westpa-mpi/src/west/sim_manager.py", line 250, in initialize_simulation
    self.data_manager.create_ibstate_group(basis_states)
  File "/opt/sam/westpa-mpi/src/west/data_manager.py", line 512, in create_ibstate_group
    state_pcoords[i] = state.pcoord
ValueError: could not broadcast input array from shape (2) into shape (1)
```

@ajoshpratt If I take your suggest to remove lines 52-54 in west.cfg I get the following error:

``` bash
php8@login0b:~/run/p53-tutorial$ ./init.sh 
simulation p53-tutorial root is /ihome/pgivi/php8/run/p53-tutorial
Creating HDF5 file '/ihome/pgivi/php8/run/p53-tutorial/west.h5'
0 target state(s) present
Calculating progress coordinate values for basis states.
1 basis state(s) present
Preparing initial states
Traceback (most recent call last):
  File "/opt/sam/westpa-mpi/lib/cmds/w_init.py", line 125, in <module>
    suppress_we=args.shotgun)
  File "/opt/sam/westpa-mpi/src/west/sim_manager.py", line 291, in initialize_simulation
    self.we_driver.populate_initial(initial_states, weights, system)
  File "/opt/sam/westpa-mpi/src/west/we_driver.py", line 616, in populate_initial
    self.construct_next()
  File "/opt/sam/westpa-mpi/src/west/we_driver.py", line 711, in construct_next
    self._run_we()
  File "/opt/sam/westpa-mpi/src/west/we_driver.py", line 554, in _run_we
    self._check_pre()
  File "/opt/sam/westpa-mpi/src/west/we_driver.py", line 535, in _check_pre
    if self.bin_target_counts[ibin] == 0 and len(_bin) > 0:
IndexError: index 1 is out of bounds for axis 0 with size 1
```

I started inserting print statements trying to figure out what is going on.  I am not too familiar with these parts of westpa.  But I will continue to drill down tomorrow.

**Comment by astatide** [comment]
Hi Patrick,

Thanks for doing all that.  It appears the issue is that the MPI version you built isn't compatible with the yaml config options that this was based off of.

It's possible that the yamlconfig interface has changed, or whatever.  Regardless, I'll push the fixed version of system.py, but in a nutshell:

uncomment lines 24-26 and 47-49

And the system should start up properly.
